### ISSUE TITLE
Búsqueda Nuevos Datasets 📝

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#15]
Teniendo en cuenta los productos que se van a entregar al cliente final, es necesario que se realice la búsqueda, extracción, transformación y cargue de nuevos datasets los cuáles deben incluir de manera preliminar:

1. Datos sobre flujo de turismo por ciudades y estados.
2. Censo poblacional por ciudad y estado.
3. Datos de segmentación y palabras claves de fuentes como Google Ads y Google Analytics, fuente para los modelos de recomendaciones.

**Comment by leydypenaloza** [comment]
Como compromiso para este nuevo Sprint # 2 se definió como tareas adicionales para esta actividad:

1. Consultar como primera instancia la web de Yelp y Google Maps para identificar nuevas fuentes de información útiles para el proyecto.
2. Consultar otras fuentes de información para generar nuevos Datasets para luego aplicar EDA y ETL
3. Como principales responsables de la ingeniería están @cistelsa y @aldemarbr94

**Comment by cistelsa** [comment]
Investigué información reciente referente al negocio de los hoteles, el objetivo era descargar datos lo más actualizado posible, revisé en kaggle pero la verdad no podemos verificar si esta data estática es real o que no esté alterada, entonces seguí mi búsqueda desde google y demás foros encontré Google Hotels pero es un servicio para los hoteles y no existe la forma de extraer data directamente sino que se debe pasar por google maps y ya poseemos data estática de este proveedor, luego encontré un sitio llamado `hotelbeds.com` el cual su documentación no se encuentra para python, entonces procedí a buscar la forma de hacer uso de la api con python y se logró desarrollar, la documentación se encuentra en el siguiente enlace:

https://developer.hotelbeds.com/documentation/hotels/booking-api/api-reference/#operation/availability

Allí encontraremos data que se filtra por fecha de checkin y checkout y por país, actualizaré pronto en este texto las columnas que da de respuesta la API:

Codigo de conexión API modo de prueba:
`import requests
import json
import time, hashlib

# Tu API Key y Secret
apiKey = "522746f91305dc7f7ab06bac5773795f"
Secret = "0e7ad9b347"

# Signature es generado por SHA256 (Api-Key + Secret + Timestamp (en segundos))
sigStr = "%s%s%d" % (apiKey, Secret, int(time.time()))
signature = hashlib.sha256(sigStr.encode()).hexdigest()

url = "https://api.test.hotelbeds.com/hotel-api/1.0/hotels"

payload = json.dumps({
  "stay": {
    "checkIn": "2023-09-28",
    "checkOut": "2023-09-29"
  },
  "occupancies": [
    {
      "rooms": 1,
      "adults": 2,
      "children": 0
    },
    {
      "rooms": 1,
      "adults": 1,
      "children": 1,
      "paxes": [
        {
          "type": "CH",
          "age": 2
        }
      ]
    }
  ],
  "hotels": {
    "hotel": [
      1533,
      1803,
      2587,
      3219,
      6930,
      69995,
      586091,
      586234
    ]
  }
})
headers = {
  'Api-key': apiKey,
  'X-Signature': signature,
  'Accept': 'application/json',
  'Accept-Encoding': 'gzip',
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)`

|-----------------|----------------|
|espacio para las columnas extraidas |   |

**Que es HotelBeds?** 
> Es una plataforma proveedora de datos para negocios y portales web que venden servicios de hoteles similar a booking.com funciona a través de una API y podemos gestionar una aplicación de reservas de hoteles haciendo escritura, pero para nuestro caso solo lo necesitamos como lectura.

`Importante:` La plataforma también maneja datos de turismo entonces invito a mis compañeros @yesicamilagros @aldemarbr94 @leydypenaloza @MayrenS95 para investigar a más profundidad si es útil esta información.

**Comment by yesicamilagros** [comment]
consultas referentes a distintos rubros del turismo (hoteles, restaurantes, bares,etc)  utilizando la api de Yelp en lenguaje  python

nota: la API KEY es necesario para hacer las llamadas realizadas en las consultas  . puede registrase a link https://www.yelp.com/login?return_url=/developers/v3/manage_app   para obtenerlas

las consultas a : 

https://api.yelp.com /v3/businesses/engagement
https://api.yelp.com /v3/businesses/ {business_id_or_alias} /service_offerings
https://api.yelp.com /v3/businesses/ {business_id_or_alias} /review_highlights
https://api.yelp.com/v3/brands/businesses _

se requiere que se habiliten permisos especiales para la clave API de Yelp Fusion (ser socios de yelp).
notebook :

https://colab.research.google.com/drive/1SITrNXyLatQLrI2MydxQeNjrSss-zgD0?usp=sharing

example : 

`import requests
import pandas as pd
import json

# Define a business ID
business_id = '4AErMBEoNzbk7Q8g45kKaQ'
unix_time = 1546047836

# Define my API Key, My Endpoint, and My Header https://docs.developer.yelp.com/reference/v3_business_search
API_KEY = 'tu_api_key'
ENDPOINT = 'https://api.yelp.com/v3/businesses/search'#.format(business_id) #https://api.yelp.com/v3/businesses/{}/reviews   https://api.yelp.com/v3/businesses/search
HEADERS = {'Authorization': 'bearer %s' % API_KEY}

PARAMETERS = {
              'latitude':37.786882,
              'longitude' : -122.399972      #localizacion de la empresas    'term': 'hotel' :
          }      #'limit': 50,
            #'radius': 10000,   47.751076, -120.740135
             #'location': 'Chicago


response = requests.get(url = ENDPOINT,params = PARAMETERS,
                        headers = HEADERS) #

# Conver the JSON String
business_data = response.json()

# print the response
print(json.dumps(business_data, indent = 1))

#dataframe
datos_df = pd.DataFrame.from_dict(business_data['businesses'])
datos_df



`

**Comment by cistelsa** [comment]
Esta tarea queda abierta para poder agregar en una próxima actualización más bases de datos importantes para lograr los objetivos, @yesicamilagros @aldemarbr94 @leydypenaloza @MayrenS95

**Comment by leydypenaloza** [comment]
Teniendo en cuenta que los datos adquiridos se pueden considerar suficientes en este punto del proyecto, se establece cerrar esta actividad y continuar con los procesos de EDA y ETL.
