### ISSUE TITLE
Filtrado Datasets de YELP 🎰

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#28]
Una vez finalizado el proceso de EDA al Dataset _Business_ de YEKP, se evidenciaron hallazgos por los cuales la data se remitió a ingeniería para proceso de ETL.

Una vez finalizado ese ETL se creó un nuevo Dataset el cual hace de base para el filtrado de los demás Datasets: _Reviews_, _CheckIn_, _Users_ y _Tips_.

Como actividad se debe utilizar la base de datos _df_busines.csv_ como index para filtrar las demás bases de datos de YELP.

**Comment by cistelsa** [comment]
## Extracción de la data original para el proceso de filtrado

Para esta tarea es necesario pensar a futuro y crear un script que nos sirva para automatizar los datos, entonces comenzamos con la extracción de los dataset de google drive que nos provee nuestro cliente;

- Reviews
- CheckIn
- Users 
- Tips

Es data estática pero  a futuro puede tener algún tipo de actualización, debemos estar preparados, se realiza el proceso en `Microsoft Fabric` ya que el manejo de estos datos a nivel local requiere de recursos importantes en el hardware, la gestión de descarga es directa de `Google Drive` al `Datalake`.
Enlace para el equipo interno al Notebook en M Fabric https://app.fabric.microsoft.com/links/4tquOIxlJx?ctid=77f8c303-ef48-412f-bbb8-089de7b82c8a&pbi_source=linkShare&experience=data-engineering

## Proceso de Filtrado

Se realiza el proceso de filtrado con Spark haciendo Inner Join a los dataframe, tener en cuenta que todo se maneja con sistemas de compresión de archivos para evitar el consumo excesivo de recursos con la librería `GZIP` y los archivos `Parquet` no necesitan la compresión ya que su sistema funciona con particiones, nodos, compresión y columnar. A continuación el enlace al Notebook exclusivamente para temas internos del proyecto:

https://app.fabric.microsoft.com/links/2VYeOo79CA?ctid=77f8c303-ef48-412f-bbb8-089de7b82c8a&pbi_source=linkShare&experience=data-engineering

Finalmente se realiza la carga de los datos ya filtrados en la ruta **`data/beta/Yelp/`**
