### ISSUE TITLE
Definición del Cliente 🏨

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#3]
Con base en la documentación del proyecto, se deberá realizar una definición de quiénes serán nuestros clientes definitivos y una sustentación del porqué fueron escogidos ellos y no otros; entiéndase como clientes el grupo o conglomerado económico que se definirá como la categoría principal hacia la cuál enfocaremos nuestras propuestas de herramientas.

_"Nuestro cliente es parte de un conglomerado de empresas de restaurantes y afines, y desean tener un análisis detallado de la opinión de los usuarios en Yelp y cruzarlos con los de Google Maps sobre hoteles, restaurantes y otros negocios afines al turismo y ocio, utilizando análisis de sentimientos, predecir cuáles serán los rubros de los negocios que más crecerán (o decaerán)"_

**Comment by MayrenS95** [comment]
https://github.com/users/cistelsa/projects/4/views/1?pane=issue&itemId=38546158

**Comment by leydypenaloza** [comment]
Actividad realizada y finalizada según requerimiento
