### ISSUE TITLE
Diccionarios de Bases de Datos 📓

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#32]
Realizar Diccionarios de las Bases de Datos de Google Maps y YELP en formato excel con el tipo de estructura establecido para la Base de Datos de HotelBeds, con el fin de unificar la presentación de los documentos.

link diccionario de Hotel_beds : [Excel aquí](https://docs.google.com/spreadsheets/d/1Cb9qUBbyXu-8US3OhfAiyZLHjSJrZstZ/edit?usp=sharing&ouid=105689737903283188966&rtpof=true&sd=true)

link diccionario google maps : [aquí](https://docs.google.com/spreadsheets/d/1r6C04wFdYgTDobdmQ2i-Z00BmhQQrvtzO5bl8P-vHfQ/edit?usp=sharing)

link diccionario yelps : [aquí](https://docs.google.com/spreadsheets/d/1tTxQvdt64IJ7q4s9trUooHPTUs-sL5KfTvnWZmVcUOA/edit?usp=sharing)

**Comment by leydypenaloza** [comment]
La actividad fue realizada por @yesicamilagros y se cargan los diccionarios en formato excel en el repositorio del proyecto, en la carpeta de documentación

**Comment by yesicamilagros** [comment]
link  diccionario general : [aqui](https://docs.google.com/spreadsheets/d/102SN8fGPo5Q46PqlFR6sOzNqWM0fRJqdCOu4FT1cJNQ/edit?usp=sharing)
