### ISSUE TITLE
Entendimiento de la situación actual 📂

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#4]
En la propuesta debe quedar manifiesto un adecuado manejo de la problemática, deben poder contextualizarla y expresar posibles análisis/ soluciones en torno a la misma.

**Comment by MayrenS95** [comment]
https://github.com/users/cistelsa/projects/4/views/1?pane=issue&itemId=38546158

**Comment by leydypenaloza** [comment]
Actividad realizada y finalizada según requerimiento
