### ISSUE TITLE
Definición de objetivos 🎏

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#5]
Los objetivos deben ser acciones concretas (verbos) que describan claramente lo
que buscan lograr con el proyecto. Desarrollar, crear, hacer, etc.

**Comment by MayrenS95** [comment]
https://github.com/users/cistelsa/projects/4/views/1?pane=issue&itemId=38546158

**Comment by leydypenaloza** [comment]
Actividad realizada y finalizada según requerimiento
