### ISSUE TITLE
Definición del Alcance 📌

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#6]
Las temáticas suelen ser amplias y pueden admitir tratamientos mucho más
abarcativos en extensión y magnitud de lo que puede realizarse durante el
desarrollo del proyecto. 
Es por esto que deberán delimitar su trabajo definiendo el alcance y las
tareas/desarrollos que puedan considerar importantes para la integridad del
proyecto pero que por complejidad o tiempo, estén fuera de alcance.
Esto último pueden plantearlo como posibilidades de continuidad del proyecto.

**Comment by MayrenS95** [comment]
https://github.com/users/cistelsa/projects/4/views/1?pane=issue&itemId=38546158
