### ISSUE TITLE
KPI's  🎯

### ISSUE THREAD

**Issue by leydypenaloza** [cistelsa/Commerce_Data_Analysis_and_Recommendations#7]
Del entendimiento de la problemática surgirán cuestiones que se buscarán
resolver con el trabajo o las herramientas desarrolladas. Estas cuestiones,
formuladas como objetivos, admitirán la creación de KPIs para evaluar su
cumplimiento. Es una tarea muy abarcativa y a la vez muy específica en torno
tanto a la problemática como al enfoque elegido.
Por ejemplo:

■ Temática: generación de CO2.
Un enfoque puede ser medir el impacto de la agricultura y el consumo de
carne animal en la generación de CO2. Un objetivo puede ser reducir la
producción de carnes animales en un 8% para 2027 y ese mismo objetivo
evaluarse mediante un KPI.
Entonces, la medición del mismo va a poder permitir tomar decisiones de
negocio basadas en datos.

■ Temática: aviones.
Comparar el retraso de todos los vuelos de la aerolínea de un semestre
con respecto a otros. Además, compararlo con el promedio de la industria.
Si se encuentra por encima, proponer una reducción de, por ejemplo, 2%
para el semestre que viene, e ir aumentando ese porcentaje de reducción
en un 1% por los próximos 5 años.

■ Los KPI's definidos en nuestro proyecto :

  
  - **Índice de satisfacción** : La opinión inmediata de los clientes tras finalizar la interacción con la empresa es una 
       buena forma de conocer su percepción sobre el servicio brindado .

  -  **NPS(net promoter score) Puntuación Neta del Promotor**  : evalúa el grado en que una persona recomienda una cierta compañía (si un cliente aprecia un servicio lo suficiente como para recomendarla a otros) % Detractores - % Promotores = NPS

- **Índice de Penetración del Mercado (MPI)** : la penetración del mercado se centra en reforzar la relación e interacción de los clientes con el servicio  a fin de aumentar el compromiso o engagement de las personas con el servicio prestado. % MPI = Clientes que accedieron al servicio / tamaño total de mercado para este servicio

- <strong>- tasa de retencion del cliente </strong>

Se trata de un porcentaje que mide cuántos clientes conserva una empresa al final de un plazo determinado, después de comparar la adquisición de nuevos clientes contra el número de clientes que se perdieron.

${Clientes\quad al \quad final \quad de \quad un \quad periodo - clientes \quad nuevos \quad adquiridos \quad durante \quad el \quad periodo \over clientes \quad al \quad comienzo \quad del \quad periodo}*100$

Supongamos que al empezar el trimestre con 100 clientes , ingresan 5 nuevos clientes durante ese tiempo y luego pierde 20 ,por lo que terminas el trimestre con 85   :

 $ PMI={85 - 5 \over 100}*100= 80 % $  es decir 80%

80% de retenecion de clientes 

- **El Coste de Adquisición del Cliente o CAC** : cuánto dinero has utilizado para capturar a nuevos clientes .CAC = (Marketing + Ventas) / Clientes Adquiridos ,

![image](https://github.com/cistelsa/Commerce_Data_Analysis_and_Recommendations/assets/102852467/5e1b0724-8cd3-4cf7-9678-d98dadfc0a3a)

 *  Crecimiento  de la organizacion o empresa en un periodo determinado  : evaluar el desempeño de cada estrategia tomada
 *  comparar indices de satisfaccion por depedencia o sucursal, por grupo de edad .
 *  mediciones de Índice de quejas o inconveniencias de los clientes

bibliografia referencial 💯 

1- https://www.beetrack.com/es/blog/nps-y-csat-son-tus-clientes-leales-y-felices-con-tu-empresa
2- https://www.toucaninsights.com/es/post/marketing-para-hoteles-los-10-principales-kpi-para-una-gestion-eficiente

**Comment by cistelsa** [comment]
https://github.com/users/cistelsa/projects/4/views/1?pane=issue&itemId=38546297

**Comment by leydypenaloza** [comment]
Se realizaron los KPI con metodología SMART:



![Image](https://github.com/cistelsa/Commerce_Data_Analysis_and_Recommendations/assets/122321719/0f6c8f80-ac7e-4ca4-b1b0-2a6c17354fcd)

![Image](https://github.com/cistelsa/Commerce_Data_Analysis_and_Recommendations/assets/122321719/56811c56-e363-4091-9b04-ae1cd8db3829)

![Image](https://github.com/cistelsa/Commerce_Data_Analysis_and_Recommendations/assets/122321719/eb92ae51-c98c-4d9e-94ff-7f47c8a76675)

Con esto se da por cumplida la actividad.
